# NodeJS Version 20
FROM node:20.12-buster-slim

# Copy Dir
COPY . ./app

# Work to Dir
WORKDIR /app

# Install pnpm
RUN npm install -g pnpm

# Install Node Package
RUN pnpm install

# Set Env
ENV NODE_ENV development

EXPOSE 8080

# Cmd script
CMD ["npm", "run", "dev"]
